CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    pin VARCHAR(4),
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pages (
    id         SERIAL PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    html       TEXT NOT NULL,
    author     VARCHAR(100) NOT NULL,
    published  VARCHAR(50)  NOT NULL,
    image      VARCHAR(500) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

INSERT INTO users (id, username, email, password_hash, pin, role)
VALUES
    (
        1,
        'admin@cslab',
        'super-admin@cslab.pt',
        '$argon2id$v=19$m=65536,t=3,p=4$G8CyHuxpyi/54vzUNM9aaA$JJnewZXxGG4O3b9XlYx27YY71GWgqj7iL0pSdaTDX78',
        '7412',
        'admin'
    ),
    (
        2,
        'training-user',
        'training-user@cslab.pt',
        '$argon2id$v=19$m=65536,t=3,p=4$cxGUJojYkmztrH1HrQjUWg$pODT08IKtdwgjANmm7Ta3UudJGeXsIXLP0cvlFK7fPs',
        NULL,
        'user'
    ),
    (
        3,
        'student-user',
        'student-user@cslab.pt',
        '$argon2id$v=19$m=65536,t=3,p=4$8YwWOt5IKLgnztc+FBh79A$3tA6PiW8YScQWB7lJl/8h2Z5gJmNQiMN1d74Yy2c/R0',
        NULL,
        'user'
    )
ON CONFLICT (id) DO NOTHING;

INSERT INTO pages (title, html, author, published, image)
SELECT
    'Welcome to CS-Lab',
    $html$
<style>
  .welcome { font-family: system-ui, sans-serif; line-height: 1.6; }
  .welcome h3 { margin: 0 0 8px; color: #6ee7b7; }
  .welcome code { padding: 2px 6px; border-radius: 4px; background: rgba(255,255,255,.08); }
  .welcome button { margin-top: 12px; padding: 8px 14px; border: 1px solid #6ee7b7; border-radius: 8px; background: transparent; color: #6ee7b7; cursor: pointer; }
</style>
<div class="welcome">
  <h3>Welcome to the CS-Lab pages</h3>
  <p>This page is rendered from raw <code>HTML</code>, styled with <code>CSS</code> and made interactive with <code>JavaScript</code>.</p>
  <button id="welcome-btn">Click me</button>
  <p id="welcome-out"></p>
</div>
<script>
  var clicks = 0;
  document.getElementById('welcome-btn').addEventListener('click', function () {
    clicks++;
    document.getElementById('welcome-out').textContent = 'Clicked ' + clicks + ' time(s)';
  });
</script>
$html$,
    'admin@cslab',
    '2026',
    '/articles/ctf.png'
WHERE NOT EXISTS (
    SELECT 1 FROM pages WHERE title = 'Welcome to CS-Lab'
);

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    GREATEST((SELECT MAX(id) FROM users), 1),
    true
);

